### ISSUE TITLE
The dataset download is not available.

### ISSUE THREAD

**Issue by appletea233** [UCSB-AI/Aerial-Vision-and-Dialog-Navigation#13]
![3231711631213_ pic](https://github.com/eric-ai-lab/Aerial-Vision-and-Dialog-Navigation/assets/77574910/4aea58bb-aaa6-4ae3-bbf7-a8958f6d4284)

As shown in the figure, below dataset download is not available.
* [Train](https://drive.google.com/file/d/1bdX5E1uEQXg8T8b5T7sh6WXb4V5rcG_Q/view?usp=sharing)
* [Validation seen](https://drive.google.com/file/d/1y0PAW3bN1KtWPx9SkKuJU7o0c0tJsnzY/view?usp=sharing)
* [Validation unseen](https://drive.google.com/file/d/1MYVAPeeS7Ydw4P7j1glvmYoE5yrN8Eo8/view?usp=sharing)

only [Test unseen](https://drive.google.com/file/d/14BijI07ukKCSDh3T_RmUG83z6Oa75M-U/view?usp=sharing) (without ground truth) is  available.

**Comment by UeFan** [comment]
Sorry for the inconvenience, the download link on the website was expired and I forgot to update them. Now I just updated them. Additionally, the download link in this repo is the newest one. Check: https://github.com/eric-ai-lab/Aerial-Vision-and-Dialog-Navigation?tab=readme-ov-file#download-data

Thanks for pointing this out.
