### ISSUE TITLE
About AVDN-full unseen testing 

### ISSUE THREAD

**Issue by alloldman** [UCSB-AI/Aerial-Vision-and-Dialog-Navigation#16]
Hello, we would like to follow your work. However, the testing method for AVDN-full unseen testing is not provided. Could you kindly provide the way for measuring the performance of AVDN-full unseen testing?  We hope to provide a more comprehensive evaluation in our paper. Thank you.

**Comment by UeFan** [comment]
Hi, thank you very much for your interest. Sorry for the missing part for ANDH-Full task. The code of this project is really outdated in terms of the style. I am planning to update the whole code repo.

At this time, if you want to test our develop models for the ANDH-Full task, please check out the data I just uploaded to Huggingface: [AVDN Data Repo](https://huggingface.co/datasets/yfan1997/AVDN). The evaluation code should not need any change as the metrics for the ANDH and ANDH-Full are the same.
