### ISSUE TITLE
Some confusion in this function——gps_to_img_corrds

### ISSUE THREAD

**Issue by qiaogh97** [UCSB-AI/Aerial-Vision-and-Dialog-Navigation#6]
Dear authors:
     I want to know the use of variable lng_ratio in this code:
https://github.com/eric-ai-lab/Aerial-Vision-and-Dialog-Navigation/blob/eb1a3fb7618bfc1fed425b595625b2f46fa97d06/src/env.py#L189-L196
     I know that gps[1] and gps_botm_left[1] stand for longtitude, so it's confusing why lat_ratio is divided here.

**Comment by UeFan** [comment]
Sorry for the confusion. Because we find that the satellite images are resized with the same ratio on both latitude and longitude (there might be a minimal difference but more like noise), we use lat_ratio all the time for simplicity.

**Comment by qiaogh97** [comment]
OK！Thank you for your reply.
