### ISSUE TITLE
How to understand calculating gt_next_pos_ratio code?

### ISSUE THREAD

**Issue by qiaogh97** [UCSB-AI/Aerial-Vision-and-Dialog-Navigation#8]
Dear authors:
     I have some difficulty when understanding these lines of code. I have known the mean of teacher_a[i][0], current_pos and corners. However, it's hard for me to know why gt_next_pos_ratio should be computed like this. Can you explain it in detail?
https://github.com/eric-ai-lab/Aerial-Vision-and-Dialog-Navigation/blob/eb1a3fb7618bfc1fed425b595625b2f46fa97d06/src/xview_et/agent.py#L484-L492
     By the way, a small question, in my opinion, the origin point is in the upper left corner, the  positive direction of the x-axis is to the right, and the positive direction of the y-axis is down. Is this correct please?
<img width="802" alt="image" src="https://github.com/eric-ai-lab/Aerial-Vision-and-Dialog-Navigation/assets/20733440/91ed58cd-d4b3-4c69-a619-660b4a146726">

**Comment by UeFan** [comment]
Let first understand gt_next_pos_ratio.
gt_next_pos_ratio is a list of two values [x,y] where x and y are in 0-1. Imagine there is a local coordinate system where the origin is the center of the current view area. The front right of the current view area corresponds to [1,1], and the back left of the current view area corresponds to [-1,-1]. So [x,y] is a point in the current view area's local coordinate. [x,y] is the position the drone is going to move to before taking the next action.

So the coordinate system in your first figure is a global coordinate, x,y there is not the x,y in the code. The general idea of the code here is to transfer the next gt view area center to a coordinate in the local coordinate system of the current view area. After the transform here, the result is a local coordinate but not in the range of 0-1. In some code after this part of code, we make sure the local coordinate is limited into 0-1.

**Comment by UeFan** [comment]
The second figure you draw is correct.

**Comment by qiaogh97** [comment]
Thank you!!!
