### ISSUE TITLE
Error returned during evalai server testing

### ISSUE THREAD

**Issue by yifeisu** [UCSB-AI/Aerial-Vision-and-Dialog-Navigation#9]
Dear authors:
I encountered an uncommon error while submitting test results on Evalai, as shown in the following figure：
![Snipaste_2023-11-02_11-12-39](https://github.com/eric-ai-lab/Aerial-Vision-and-Dialog-Navigation/assets/92625239/fc7925db-6d73-4284-afac-007751117b35)
Can you explain why this is happening? I have generated the test trajectory in the correct manner.

**Comment by UeFan** [comment]
Sorry for the bug, I have fixed it. Now when you submit this file, there won't be any error anymore. I re-evaluate your submission and the evaluation result is the same as shown in the error message.

**Comment by yifeisu** [comment]
Thanks very much for your timely response and maitaince!!

**Comment by yifeisu** [comment]
Thanks very much for your timely response and maitaince!!
